apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-config
  labels:
    {{- include "order-service.labels" . | nindent 4 }}
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "{{ .Values.redis.service.port }}"
