apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9100"
    spec:
      initContainers:
        - name: wait-for-redis
          image: redis:7-alpine
          command:
            - sh
            - -c
            - until redis-cli -h redis -p 6379 ping; do sleep 1; done
      containers:
        - name: worker
          image: order-service-worker:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9100
              name: metrics
          envFrom:
            - configMapRef:
                name: order-service-config
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
